---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
      when: ansible_os_family == 'Debian'
  tasks:
    - name: "Include ansible-role-python3"
      include_role:
        name: "ansible-role-python3"
