---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: amz2
    image: amazonlinux:latest
  - name: amz201803
    image: amazonlinux:2018.03
  - name: EL7
    image: centos:7
  - name: Xenial
    image: ubuntu:16.04
  - name: Bionic
    image: ubuntu:18.04
  - name: Focal
    image: ubuntu:20.04
  - name: EL8
    image: centos:8
provisioner:
  name: ansible
verifier:
  name: ansible
